### ISSUE TITLE
1minute bar range issue

### ISSUE THREAD

**Issue by boyuhou** [tibkiss/iqfeed#1]
Hi, thanks for putting this nice feature together. In an attempt to verify the result, I noticed that the function get_bars in download.py use time filter 09:29 to 15:59, i think (only based on observation), the minute bar in IQFeed means the bar from previous defined seconds up to that time. In our case, 09:30 bar means data from 09:29 to 09:30 and 15:59 means bar from 15:58 to 15:59. The drawback of it is that if we aggregate the minute bars to get daily open and close, the numbers are not accurate. I used the following (TICKER: EWZ) as a test, here is two lines I get from the file:
DateTime,Open,High,Low,Close,Volume
20161104 093000,35.55,35.55,35.55,35.55,138622
20161104 093100,35.53,35.545,35.39,35.41,678595
20161104 155900,35.355,35.37,35.34,35.345,18997559

if we check google or yahoo for 20161104 open and close, i have the following:
Date	                Open	High	        Low	        Close	Volume
Nov 4, 2016	35.53	36.11	35.18	35.36	20,544,162

You can see that the Open is what we have on 20161104093100 and the Close is not matched. 
I believe simply change the filter time to 0930 and 1600 will solve this problem.

**Comment by tibkiss** [comment]
@boyuhou:
Thanks for reporting this issue. IIRC I needed to specify the datetimes as 9:29 and 15:59 to get correct daily results. 

Currently I do not have IQFeed access therefore I cannot validate your assumption directly.
I do have access realtime & historical data through other provider (IB). 

If you have IQFeed access I'd suggest that you download yesterday's prices for SPY using both the original (9:29 & 15:59) and your proposed (9:30 & 16:00) timestamps, I load it from IB then we cross-check. 

Is this sounds reasonable to you?
